name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "**.md"
      - "**.yml"
      - "LICENSE-**"
      - ".gitmessage"
      - ".pre-commit-config.yaml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "**.md"
      - "**.yml"
      - "LICENSE-**"
      - ".pre-commit-config.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  package-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install
      run: |
        rustup update stable
        cargo install --path .
    # TODO:
    # - name: boto3
    #   continue-on-error: true
    #   run: |
    #     pip3 install boto3
    #     pylyzer -c "import boto3"
    - name: urllib3
      run: |
        pip3 install urllib3
        pylyzer -c "import urllib3" || true
    - name: setuptools
      run: |
        pip3 install setuptools
        pylyzer -c "import setuptools" || true
    # TODO:
    # - name: requests
    #   run: |
    #     pip3 install requests
    #     pylyzer -c "import requests" || true
    - name: certifi
      run: |
        pip3 install certifi
        pylyzer -c "import certifi" || true
    - name: charset-normalizer
      run: |
        pip3 install charset-normalizer
        pylyzer -c "import charset_normalizer" || true
    - name: idna
      run: |
        pip3 install idna
        pylyzer -c "import idna" || true
